package onion.open.hibernate.entity;
// Generated 2016-8-7 12:38:52 by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdInfo generated by hbm2java
 */
@Entity
@Table(name = "id_info", catalog = "onion")
public class IdInfo implements java.io.Serializable {

	private Integer id;
	private String identityNum;
	private Set<User> users = new HashSet<User>(0);

	public IdInfo() {
	}

	public IdInfo(String identityNum) {
		this.identityNum = identityNum;
	}

	public IdInfo(String identityNum, Set<User> users) {
		this.identityNum = identityNum;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "identity_num", nullable = false, length = 45)
	public String getIdentityNum() {
		return this.identityNum;
	}

	public void setIdentityNum(String identityNum) {
		this.identityNum = identityNum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idInfo")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
